### PR TITLE
new 2DCNN for radio bkg rejection and 1D denoising AE, and other updates

### PR DESCRIPTION
**Pull request by mhlswang**
new 2DCNN-based model for looking at raw wire frames to reject frames containing only radiological backgrounds
new 1D denoising autoencoder to be used in conjuntion with 1DCNN ROI finder
updated 1DCNN ROI finder code to allow reconfiguring waveform size on the fly and provided new method for abitrary waveform sizes

### CODE REVIEW

**Comment by mhlswang** [comment]
As @lgarren requested, I have done some very basic checks to see if things work with tensorflow 2.15 in larsoft v09_86_00.  I verified that the models load properly.  For more thorough tests, we would have to wait for dunesw to catch up to larsoft v09_86_00 since my modules that use these features all require dunesw.  dunesw is currently at v09_83_01d00.

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
@mhlswang The build has failed on c14.  
https://dbweb8.fnal.gov:8443/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22157&builds=
I note that the latest tensorflow does not have a c14 build.  You may need to make sure it it available before building.  This check should already be in place for existing code that depends on tensorflow.

**Comment by knoepfel** [comment]
trigger build

**Comment by lgarren** [comment]
@mhlswang  The c14 build is failing.  There appears to be an unused variable in` larrecodnn/ImagePatternAlgs/ToolInterfaces/IWaveformDenoise.h`.  Please take a look.

**Comment by mhlswang** [comment]
@lgarren I looked at my code and I see that variable it is complaining about - fCnnPredCut -- is actually being used in several place in the code by methods in the class, so I am not sure why it is complaining about this:

`2868: /scratch/workspace/lar_ci/label_exp/SLF7/label_exp2/swarm/LArSoft/srcs/larrecodnn/larrecodnn/ImagePatternAlgs/ToolInterfaces/IWaveformDenoise.h:179:11: error: private field 'fCnnPredCut' is not used [-Werror,-Wunused-private-field]
2869:     float fCnnPredCut;
2870:           ^
`

**Comment by lgarren** [comment]
@mhlswang `fCnnPredCut` is defined in three separate headers:
- larrecodnn/ImagePatternAlgs/ToolInterfaces/IWaveformRecog.h
- larrecodnn/ImagePatternAlgs/ToolInterfaces/IWireframeRecog.h
- larrecodnn/ImagePatternAlgs/ToolInterfaces/IWaveformDenoise.h

There is no evidence that the definition in `IWaveformDenoise.h` is used anywhere.

**Comment by mhlswang** [comment]
@lgarren yes you are right, sorry I was looking at the wrong file.  I've fixed it.

**Comment by lgarren** [comment]
code-checks

**Comment by lgarren** [comment]
trigger build

**Comment by lgarren** [comment]
approve
